### ISSUE TITLE
Way to only consider even mapping

### ISSUE THREAD

**Issue by pch0561** [ZigZag-Project/zigzag-v1#11]
As far as I know, zigzag considers both even and uneven mapping. 
(that's why the zigzag's result mapping shows that the loop prime factor is allocated in different memory components by data type(I/W/O) )
But I want to restrict the temporal mapping generator to consider only even mapping.
Is there way to do that? 

Thanks.

**Comment by asyms** [comment]
Hi!

Even mapping is now explicitly supported in the settings. See inputs/settings.yaml.
Keep in mind this only works with LOMA as the temporal mapping search method.
The resulting mapping will be an even mapping, where each loop is allocated to a certain memory level. Because of the way mappings are represented in ZigZag you will still have to convert it it to an even mapping representation. But as I said, the LOMA search will restrict the memory allocation of each ordering as such that it only generates even mappings.
