### ISSUE TITLE
Questions about settings parameters and some metrics

### ISSUE THREAD

**Issue by suyashbakshi** [ZigZag-Project/zigzag-v1#19]
Hello, I have a few questions about some parameters and metrics:

1. Does the "spatial_utilization_threshold" apply for total number of spatial iterations? I found the following spatial mapping for an architecture with 16x16 = 256 PEs by setting the threshold to 0.85:  ```[(5,2), (5,7), (2,7), (4,2)] == 196 PEs```, which is ~76% utilization.
Could you please clear this for me?

2. In utilization.py, the variable "mac_utilize_no_load" is computed by mac_utilize_spatial and mac_utilize_temporal. I partly understand mac_utilize_spatial is simply the % of PEs actually used by the mapping (my previous question basically). But it is a bit hard to understand which "stalls" specifically does the mac_utilize_temporal constitute of? Is it just the stalls due to low available memory bandwidth?
3. Continuing on '2.', I understand these stalls are also included for the "latency" calculation, correct?

4. The "total energy" of a mapping is only a weighted sum of number of computations and memory accesses, correct? In other words, only the dynamic energy consumption. I believe it does not include any static energy consumption because of the stalls.

I'd greatly appreciate help on this.

**Comment by LY-Mei** [comment]
Hi FireBird,

1. Could you tell me which spatial mapping search method did you apply and what are your NN layer dimensions' sizes?
2. Yes, mac_utilize_spatial is simply the % of PEs actually used by the mapping. mac_utilize_temporal is due to the low available memory bandwidth / memory ports.
3. Yes. Basically, the whole latency calculation is to get the correct temporal stalling cycle count.
4. Good point. We don't consider static energy for now.

Best regards,
Linyan

**Comment by suyashbakshi** [comment]
Thanks. For 1, I used heuristic_v2 to find the spatial mapping. The layer dimensions were: K=65, C=28, OX=OY=68, FX=FY=7

**Comment by LY-Mei** [comment]
The issue is solved in the code now. Thank you for catching it!

**Comment by suyashbakshi** [comment]
Sorry its a bit unclear. Which of the specific issue has been corrected now?

**Comment by suyashbakshi** [comment]
So now, the product of all spatial unrolling factors are considered for the spatial utilization correct?

**Comment by LY-Mei** [comment]
Yes. 

Originally, the spatial utilization threshold was used to check for each PE array dimension, i.e. if you set it to 0.85, ZigZag will make sure each array dimension (16) is more than 85% utilized, so overall it will make sure the utilization to be more than 85%*85%=72.25%. That explains why you get a spatial utilization of 76%. 

Now we have changed the threshold be to used for the whole array, instead of for each dimension of the array. If you rerun the same case, you won't get that 76% SU anymore.

**Comment by suyashbakshi** [comment]
Thank you. I have a follow-up question. Could you please explain the use of "flooring" in the spatial unrolling?
Does that cause significant differences between the mapping costs? If so, how?

**Comment by LY-Mei** [comment]
Flooring is used to identify for each dimension of the 2D PE array, what loops are unrolled on it. It doesn't make difference in the cost.
