### ISSUE TITLE
Possible bug + fix for s_loop_name_transfer in output_funcs

### ISSUE THREAD

**Issue by MikeStorms** [ZigZag-Project/zigzag-v1#2]
Hello!

I'm currently using the ZigZag tool for my masters thesis. While simulating a fixed architecture, variable loop unrolling and temporal mapping the following error occured. 
> Traceback (most recent call last):
  File "/users/start2017/r0653464/Documents/Thesis/zigzag-master/output_funcs.py", line 493, in print_xml
    spatial_mapping_W.tail = str(s_loop_name_transfer(cost_model_output.spatial_scheme['W']))
  File "/users/start2017/r0653464/Documents/Thesis/zigzag-master/output_funcs.py", line 70, in s_loop_name_transfer
TypeError: 'int' object is not subscriptable

By debugging these errors. I think I found the source and a possible solution. 
In the `s_loop_name_transfer` function, the variable `mapping` is given as an input. An example of this, with the correct structure is `[[], [[3, 7], [5, 8], [1, 3]], [], []]` 
The function consists of 3 for loops which all go 1 level deeper in the nested array. At the end the fucntion ` post_mapping[-1][-1].append((loop_name[va[0]], va[1]))` is called. The `va` variables however are the integers inside the nested for loops. These are accesed again like an array, which is not possible. 
A **fix** is to delete the final for loop and to switch `va[0], va[1]` with `inner_li[0], inner_li[1]`.
I think this is the intended solution  because it switches the first integer with the respective loop name.

Best regards,
Mike Storms

**Comment by LY-Mei** [comment]
Hi Mike,

Thank you for selecting our tool for your master thesis!
I have tested the code and cannot repeat the same problem you have. To fix it, you can do the following quick checks:
1) Are you using the newest version of the code? If not, rerun it with the newest version. If the error is still there, go to 2.
2) The correct data format that function `s_loop_name_transfer ` expects is like [[], [[[3, 7], [5, 8]], [[1, 3]]], [], []] or [[], [[[3, 7]], [[5, 8], [1, 3]]], [], []], which not only indicates which loops are unrolled at which arch level, but also tells which loops are unrolled along which PE array dimension (row or colunm). For example, [[], [[[3, 7], [5, 8]], [[1, 3]]], [], []] means loop 3 (OX) and loop 5 (C) are unrolled along the row 7 and 8 times resp., and loop 1 (FX) is unrolled along the colunm 3 times (in this case, the active PE array size is 56 x 3). To make this transfer, from `[[], [[3, 7], [5, 8], [1, 3]], [], []]` to `[[], [[[3, 7], [5, 8]], [[1, 3]]], [], []]`, function `spatial_loop_same_term_merge ` in the output_funcs.py is called, which incorporate such unrolling layout information into spatial mapping from a parameter called `cost_model_output.flooring`. You need to check why this function is not triggered in your situation (e.g. put some breaking points and check the code execution flow). Most likely, I guess, your spatial-mapping-related input settings are not fully correct.
3) If the issue is still there, you can post or email me your 4 input setting files. I will have a look.

Best regards,
Linyan

**Comment by MikeStorms** [comment]
Thank you, it seemed the version i was using was not up to date. Weird, as other networks did compute, nevertheless its fixed now!

**Comment by LY-Mei** [comment]
ok!
